{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c275663c-f2c4-40c7-9b3d-dbf692b8ac45",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pymongo\n",
      "  Downloading pymongo-4.3.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (492 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m492.9/492.9 kB\u001b[0m \u001b[31m3.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting dnspython<3.0.0,>=1.16.0 (from pymongo)\n",
      "  Downloading dnspython-2.3.0-py3-none-any.whl (283 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m283.7/283.7 kB\u001b[0m \u001b[31m5.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: dnspython, pymongo\n",
      "Successfully installed dnspython-2.3.0 pymongo-4.3.3\n"
     ]
    }
   ],
   "source": [
    "!pip install pymongo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ea08843f-728e-49b9-8251-25ba8ed97b25",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import pymongo\n",
    "\n",
    "\n",
    "client= pymongo.MongoClient('mongodb://root:example@mongodb:27017/admin?authSource=admin')\n",
    "\n",
    "db = client['test']\n",
    "\n",
    "# https://stackoverflow.com/a/70066599/2987581\n",
    "try:\n",
    "    db.command('createUser', 'myTester', pwd='tester123', roles=[{'role':'readWrite','db':'test'}, { 'role': \"read\", 'db': \"reporting\" }])\n",
    "except pymongo.errors.OperationFailure as e:\n",
    "    if e.code == 51003: # Duplicate user error code pymongo.errors.OperationFailure: User \"jdoe@mydatabase\" already exists, full error: {'ok': 0.0, 'errmsg': 'User \"jdoe@mydatabase\" already exists', 'code': 51003, 'codeName': 'Location51003'}\n",
    "        print(f\"User myTester exists\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a1ecd6fa-26f9-4bc4-a2b7-3769f868b084",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "admin\n",
      "config\n",
      "local\n",
      "Before\n",
      "after\n",
      "{'_id': ObjectId('645f3f1c5387f06473892bb6'), 'source': 'some_source'}\n"
     ]
    }
   ],
   "source": [
    "for somedb in client.list_database_names():\n",
    "    print(somedb)\n",
    "    \n",
    "mycol = db[\"mytest_collection\"]\n",
    "\n",
    "print(\"Before\")\n",
    "for doc in db.mytest_collection.find():\n",
    "    print(doc)\n",
    "\n",
    "mycol.insert_one({\"source\": 'some_source'})\n",
    "\n",
    "print(\"after\")\n",
    "for doc in db.mytest_collection.find():\n",
    "    print(doc)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "86c0afc7-f206-482b-9c7d-9ae7bcb76df8",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "admin\n",
      "config\n",
      "local\n",
      "test\n"
     ]
    }
   ],
   "source": [
    "for somedb in client.list_database_names():\n",
    "    print(somedb)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "705debed-a473-44f1-9e8b-1aa4bac32dee",
   "metadata": {},
   "source": [
    "**Now we have to run the dag!!!**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ea19391f-8910-4aaa-a754-a043c55be5aa",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dag has been run\n",
      "{'_id': ObjectId('645f3f1c5387f06473892bb6'), 'source': 'some_source', 'processed': True}\n"
     ]
    }
   ],
   "source": [
    "print(\"dag has been run\")\n",
    "for doc in db.mytest_collection.find():\n",
    "    print(doc)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e47060a5-15f1-4d20-8b18-605936bed342",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# https://stackoverflow.com/a/70066599/2987581\n",
    "try:\n",
    "    db.command('dropUser', 'newTestUser')\n",
    "except pymongo.errors.OperationFailure as e:\n",
    "    if e.code == 11: # Duplicate user error code pymongo.errors.OperationFailure: User \"jdoe@mydatabase\" already exists, full error: {'ok': 0.0, 'errmsg': 'User \"jdoe@mydatabase\" already exists', 'code': 51003, 'codeName': 'Location51003'}\n",
    "        print(f\"User newTestUser not found\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
